node {
    withCredentials([
        string(credentialsId: 'SPRING_APP_NEW_RELIC_KEY', variable: 'NEW_RELIC_KEY')
    ]) {
        stage('Show Docker Contexts') {
            echo 'Listing Docker contexts...'
            sh 'docker context ls'
            echo 'Current Docker context:'
            sh 'docker context show'
        }

        stage('Generate newrelic.yml') {
            dir('spring_boot_service/newrelic') {
                sh '''
                export NEW_RELIC_LICENSE_KEY="$NEW_RELIC_KEY"
                envsubst < newrelic_template.yml > newrelic.yml
                '''
            }
        }

        stage('Build Docker Image') {
            dir('spring_boot_service') {
                script {
                    dockerImage = docker.build("spring_boot_iot:latest", "--no-cache .")
                }
            }
        }
    }

    echo 'Spring boot build Pipeline finished.'
}
