node {
    stage('Show Docker Contexts') {
        echo 'Listing Docker contexts...'
        sh 'docker context ls'
        echo 'Current Docker context:'
        sh 'docker context show'
    }

    stage('Verify File Presence') {
        echo "Current directory: ${pwd()}"
        sh 'ls -l'
    }

    stage('Generate newrelic.ini') {
        dir('python_iot') {
            withCredentials([string(credentialsId: 'PYTHON_NEW_RELIC_KEY_CRED', variable: 'NEW_RELIC_KEY')]) {
                sh '''
                export PYTHON_NEW_RELIC_LICENSE_KEY="$NEW_RELIC_KEY"
                envsubst < newrelic_template.ini > newrelic.ini
                '''
            }
        }
    }

    stage('Build Docker Image') {
        dir('python_iot') {
            dockerImage = docker.build("python-iot-device:latest", "--no-cache .")
        }
    }

    echo 'Python IOT Build completed.'
}
