node {
    // Environment variables from Jenkins credentials
    withCredentials([
        string(credentialsId: 'REACT_APP_PIXBAY_KEY', variable: 'REACT_APP_PIXBAY_KEY'),
        string(credentialsId: 'REACT_APP_CLERK_PUBLISHABLE_KEY', variable: 'REACT_APP_CLERK_PUBLISHABLE_KEY'),
        string(credentialsId: 'REACT_APP_HOST_URL', variable: 'REACT_APP_HOST_URL')
    ]) {
        stage('Show Docker Contexts') {
            echo 'Listing Docker contexts...'
            sh 'docker context ls'
            echo 'Current Docker context:'
            sh 'docker context show'
        }

        stage('Build Docker Image') {
            dir('react_app') {
                script {
                    def buildArgs = "--build-arg REACT_APP_PIXBAY_KEY=${env.REACT_APP_PIXBAY_KEY} " +
                                    "--build-arg REACT_APP_CLERK_PUBLISHABLE_KEY=${env.REACT_APP_CLERK_PUBLISHABLE_KEY} " +
                                    "--build-arg REACT_APP_HOST_URL=${env.REACT_APP_HOST_URL} ."
                    dockerImage = docker.build("react_iot:latest", buildArgs)
                }
            }
        }
    }

    echo 'React App build finished.'
}
