apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: home-iot
spec:
  selector:
    app: home-iot-springboot
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30978
